// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for ResponseCode.
const (
	CHECKFAILED       ResponseCode = "CHECK_FAILED"
	OK                ResponseCode = "OK"
	RATELIMITEXCEEDED ResponseCode = "RATE_LIMIT_EXCEEDED"
)

// Defines values for ServerInfoType.
const (
	Arcade ServerInfoType = "arcade"
	Mcp    ServerInfoType = "mcp"
)

// AccessHookRequest Access-hook request from engine to hook server
type AccessHookRequest struct {
	// Toolkits Map of toolkit name to toolkit info
	Toolkits Toolkits `json:"toolkits"`

	// UserId User ID
	UserId string `json:"user_id"`
}

// AccessHookResult Access-hook response from hook server to engine. If 'allow' is included, ONLY those are allowed (deny list ignored).
type AccessHookResult struct {
	// Allow Map of toolkit name to toolkit info
	Allow *Toolkits `json:"allow,omitempty"`

	// Deny Map of toolkit name to toolkit info
	Deny *Toolkits `json:"deny,omitempty"`
}

// Authorization Authorization information
type Authorization struct {
	// Oauth2 OAuth2 authorization details
	Oauth2 *OAuth2Details `json:"oauth2,omitempty"`

	// ProviderId ID of the OAuth provider
	ProviderId *string `json:"provider_id,omitempty"`
}

// ErrorResponse Error response from webhook server
type ErrorResponse struct {
	// Code Machine-readable error code for programmatic handling
	Code *string `json:"code,omitempty"`

	// Error Human-readable error message
	Error *string `json:"error,omitempty"`
}

// HealthResponse Health check response
type HealthResponse struct {
	// Status Health status
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus Health status
type HealthResponseStatus string

// OAuth2Details OAuth2 authorization details
type OAuth2Details struct {
	// At Access token claims (only present when token is a JWT; absent for opaque tokens)
	At *map[string]interface{} `json:"at,omitempty"`

	// Scopes OAuth scopes (always available from token response)
	Scopes *[]string `json:"scopes,omitempty"`

	// UserInfo User information from oauth2 provider
	UserInfo *map[string]interface{} `json:"user_info,omitempty"`
}

// PostHookOverride Override response parameters
type PostHookOverride struct {
	// Output Override the response returned
	Output *map[string]interface{} `json:"output,omitempty"`
}

// PostHookRequest Post-hook request from engine to hook server
type PostHookRequest struct {
	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionCode Status code from the worker
	ExecutionCode *string `json:"execution_code,omitempty"`

	// ExecutionError Execution error from the tool call
	ExecutionError *string `json:"execution_error,omitempty"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Inputs Tool inputs (name -> value)
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Output The execution output
	Output map[string]interface{} `json:"output"`

	// Server Server routing information
	Server ServerInfo `json:"server"`

	// Success Whether the tool succeeded
	Success *bool `json:"success,omitempty"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PostHookResult Post-hook response from hook server to engine
type PostHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the LLM
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override response parameters
	Override *PostHookOverride `json:"override,omitempty"`
}

// PreHookOverride Override execution parameters
type PreHookOverride struct {
	// Headers Override request headers
	Headers *map[string]string `json:"headers,omitempty"`

	// Inputs Override tool inputs
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Secrets Override secrets
	Secrets *[]map[string]string `json:"secrets,omitempty"`

	// Server Server routing information
	Server *ServerInfo `json:"server,omitempty"`
}

// PreHookRequest Pre-hook request from engine to hook server
type PreHookRequest struct {
	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Headers Headers from the incoming tool request
	Headers *map[string]string `json:"headers,omitempty"`

	// Inputs Tool inputs (name -> value)
	Inputs map[string]interface{} `json:"inputs"`

	// Servers Server routing information for pre-hook
	Servers Servers `json:"servers"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PreHookResult Pre-hook response from hook server to engine
type PreHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the LLM
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override execution parameters
	Override *PreHookOverride `json:"override,omitempty"`
}

// ResponseCode Response code from hook server
type ResponseCode string

// SecretRequirement Required secret definition
type SecretRequirement struct {
	// Name Secret name
	Name string `json:"name"`
}

// ServerInfo Server routing information
type ServerInfo struct {
	// Name Server name
	Name string `json:"name"`

	// Type Server type
	Type ServerInfoType `json:"type"`

	// Uri Server URI
	Uri string `json:"uri"`
}

// ServerInfoType Server type
type ServerInfoType string

// Servers Server routing information for pre-hook
type Servers struct {
	// Available Available servers with same structure
	Available *[]ServerInfo `json:"available,omitempty"`

	// Destination Server routing information
	Destination *ServerInfo `json:"destination,omitempty"`
}

// ToolContext Tool execution context
type ToolContext struct {
	Authorization *[]Authorization `json:"authorization,omitempty"`

	// Metadata Arbitrary metadata from tool
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Secrets Required secrets (key only, no values)
	Secrets *[]string `json:"secrets,omitempty"`

	// UserId User ID for access checks
	UserId *string `json:"user_id,omitempty"`
}

// ToolInfo Tool identification information
type ToolInfo struct {
	// Name Tool name
	Name string `json:"name"`

	// Toolkit Toolkit name
	Toolkit string `json:"toolkit"`

	// Version Tool version
	Version string `json:"version"`
}

// ToolVersionInfo Version-specific information for a tool
type ToolVersionInfo struct {
	// Requirements Requirements for a tool
	Requirements *ToolkitRequirements `json:"requirements,omitempty"`

	// Version Tool version
	Version *string `json:"version,omitempty"`
}

// ToolkitAuthRequirements Authorization requirements for a toolkit
type ToolkitAuthRequirements struct {
	Oauth2 *struct {
		// Scopes Required scopes
		Scopes *[]string `json:"scopes,omitempty"`
	} `json:"oauth2,omitempty"`

	// ProviderId Provider ID
	ProviderId *string `json:"provider_id,omitempty"`

	// ProviderType Provider type
	ProviderType *string `json:"provider_type,omitempty"`
}

// ToolkitInfo Toolkit information with tools
type ToolkitInfo struct {
	// Tools Map of tool name to array of tool version info (there may be multiple versions of tools)
	Tools *map[string][]ToolVersionInfo `json:"tools,omitempty"`
}

// ToolkitRequirements Requirements for a tool
type ToolkitRequirements struct {
	// Authorization Authorization requirements for a toolkit
	Authorization *[]ToolkitAuthRequirements `json:"authorization,omitempty"`

	// Secrets Required secrets
	Secrets *[]SecretRequirement `json:"secrets,omitempty"`

	// Server Server routing information
	Server *ServerInfo `json:"server,omitempty"`
}

// Toolkits Map of toolkit name to toolkit info
type Toolkits map[string]ToolkitInfo

// AccessHookJSONRequestBody defines body for AccessHook for application/json ContentType.
type AccessHookJSONRequestBody = AccessHookRequest

// PostHookJSONRequestBody defines body for PostHook for application/json ContentType.
type PostHookJSONRequestBody = PostHookRequest

// PreHookJSONRequestBody defines body for PreHook for application/json ContentType.
type PreHookJSONRequestBody = PreHookRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AccessHookWithBody request with any body
	AccessHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AccessHook(ctx context.Context, body AccessHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHookWithBody request with any body
	PostHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHook(ctx context.Context, body PostHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PreHookWithBody request with any body
	PreHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PreHook(ctx context.Context, body PreHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AccessHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAccessHookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AccessHook(ctx context.Context, body AccessHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAccessHookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHook(ctx context.Context, body PostHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PreHookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreHookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PreHook(ctx context.Context, body PreHookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreHookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAccessHookRequest calls the generic AccessHook builder with application/json body
func NewAccessHookRequest(server string, body AccessHookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAccessHookRequestWithBody(server, "application/json", bodyReader)
}

// NewAccessHookRequestWithBody generates requests for AccessHook with any type of body
func NewAccessHookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/access")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHookRequest calls the generic PostHook builder with application/json body
func NewPostHookRequest(server string, body PostHookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHookRequestWithBody(server, "application/json", bodyReader)
}

// NewPostHookRequestWithBody generates requests for PostHook with any type of body
func NewPostHookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/post")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPreHookRequest calls the generic PreHook builder with application/json body
func NewPreHookRequest(server string, body PreHookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPreHookRequestWithBody(server, "application/json", bodyReader)
}

// NewPreHookRequestWithBody generates requests for PreHook with any type of body
func NewPreHookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pre")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AccessHookWithBodyWithResponse request with any body
	AccessHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AccessHookResponse, error)

	AccessHookWithResponse(ctx context.Context, body AccessHookJSONRequestBody, reqEditors ...RequestEditorFn) (*AccessHookResponse, error)

	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// PostHookWithBodyWithResponse request with any body
	PostHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHookResponse, error)

	PostHookWithResponse(ctx context.Context, body PostHookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHookResponse, error)

	// PreHookWithBodyWithResponse request with any body
	PreHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PreHookResponse, error)

	PreHookWithResponse(ctx context.Context, body PreHookJSONRequestBody, reqEditors ...RequestEditorFn) (*PreHookResponse, error)
}

type AccessHookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccessHookResult
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r AccessHookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AccessHookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *ErrorResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostHookResult
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostHookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PreHookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PreHookResult
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PreHookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PreHookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AccessHookWithBodyWithResponse request with arbitrary body returning *AccessHookResponse
func (c *ClientWithResponses) AccessHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AccessHookResponse, error) {
	rsp, err := c.AccessHookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAccessHookResponse(rsp)
}

func (c *ClientWithResponses) AccessHookWithResponse(ctx context.Context, body AccessHookJSONRequestBody, reqEditors ...RequestEditorFn) (*AccessHookResponse, error) {
	rsp, err := c.AccessHook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAccessHookResponse(rsp)
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// PostHookWithBodyWithResponse request with arbitrary body returning *PostHookResponse
func (c *ClientWithResponses) PostHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHookResponse, error) {
	rsp, err := c.PostHookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHookResponse(rsp)
}

func (c *ClientWithResponses) PostHookWithResponse(ctx context.Context, body PostHookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHookResponse, error) {
	rsp, err := c.PostHook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHookResponse(rsp)
}

// PreHookWithBodyWithResponse request with arbitrary body returning *PreHookResponse
func (c *ClientWithResponses) PreHookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PreHookResponse, error) {
	rsp, err := c.PreHookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePreHookResponse(rsp)
}

func (c *ClientWithResponses) PreHookWithResponse(ctx context.Context, body PreHookJSONRequestBody, reqEditors ...RequestEditorFn) (*PreHookResponse, error) {
	rsp, err := c.PreHook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePreHookResponse(rsp)
}

// ParseAccessHookResponse parses an HTTP response from a AccessHookWithResponse call
func ParseAccessHookResponse(rsp *http.Response) (*AccessHookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AccessHookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccessHookResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParsePostHookResponse parses an HTTP response from a PostHookWithResponse call
func ParsePostHookResponse(rsp *http.Response) (*PostHookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostHookResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePreHookResponse parses an HTTP response from a PreHookWithResponse call
func ParsePreHookResponse(rsp *http.Response) (*PreHookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PreHookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PreHookResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Access control hook
	// (POST /access)
	AccessHook(c *gin.Context)
	// Health check endpoint
	// (GET /health)
	HealthCheck(c *gin.Context)
	// Post-execution hook
	// (POST /post)
	PostHook(c *gin.Context)
	// Pre-execution hook
	// (POST /pre)
	PreHook(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AccessHook operation middleware
func (siw *ServerInterfaceWrapper) AccessHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AccessHook(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// PostHook operation middleware
func (siw *ServerInterfaceWrapper) PostHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostHook(c)
}

// PreHook operation middleware
func (siw *ServerInterfaceWrapper) PreHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PreHook(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/access", wrapper.AccessHook)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
	router.POST(options.BaseURL+"/post", wrapper.PostHook)
	router.POST(options.BaseURL+"/pre", wrapper.PreHook)
}
